# Generated by Django 4.2.20 on 2025-04-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='1', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
